In [1]:
import numpy as np

In [2]:
def Orders(array, start, end):
  if len(start) == 0:
    array.append(end)
  else:
    n = len(start)
    for i in range(n):
      nextEnd = end + start[i:i+1]
      nextStart = start[:i] + start[i+1:]
      Orders(array, nextStart, nextEnd)

In [3]:
array = []
start = [0,1,2,3,4,5,6]
MenPreferences = [[5, 6, 4, 2, 0, 3, 1], [0, 5, 1, 2, 4, 3, 6], [3, 6, 1, 2, 5, 0, 4], [1, 2, 5, 0, 6, 4, 3], [6, 0, 2, 4, 3, 1, 5], [2, 1, 4, 0, 3, 6, 5], [5, 6, 4, 2, 0, 1, 3]]
WomenPreferences = [[0, 4, 3, 1, 5, 2, 6], [5, 1, 4, 6, 3, 2, 0], [1, 5, 4, 2, 6, 3, 0], [0, 1, 4, 5, 3, 2, 6], [5, 2, 4, 1, 0, 6, 3], [5, 6, 3, 2, 0, 1, 4], [2, 6, 5, 3, 4, 0, 1]]

In [4]:
Orders(array, start, [])

In [5]:
array = np.array(array)
MenPreferences = np.array(MenPreferences)
WomenPreferences = np.array(WomenPreferences)

In [6]:
count = 0
result = []
dBreak = False
for ordering in array:
  dBreak = False
  for m1, w1 in enumerate(ordering):
    r1 = np.where(MenPreferences[m1] == w1)[0][0]
    r2 = np.where(WomenPreferences[w1] == m1)[0][0]

    for w2 in MenPreferences[m1,:r1]:
      r3 = np.where(WomenPreferences[w2] == m1)[0][0]
      if r3 < r2:
        dBreak = True
        break

    for m2 in WomenPreferences[w1,:r2]:
      r4 = np.where(MenPreferences[m2] == w1)[0][0]
      if r4 < r1:
        dBreak = True
        break
    
    if dBreak == True:
      break

  if dBreak == False:
    count +=1
    result.append(ordering)

In [7]:
count

5

In [8]:
result

[array([0, 2, 3, 1, 6, 4, 5]),
 array([3, 2, 6, 1, 0, 4, 5]),
 array([4, 0, 3, 1, 6, 2, 5]),
 array([4, 2, 3, 1, 0, 5, 6]),
 array([5, 2, 3, 1, 0, 4, 6])]